/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fang_key_CheckKey */

#ifndef _Included_fang_key_CheckKey
#define _Included_fang_key_CheckKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fang_key_CheckKey
 * Method:    checkKeyFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fang_key_CheckKey_checkKeyFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     fang_key_CheckKey
 * Method:    getCpuSerial
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fang_key_CheckKey_getCpuSerial
  (JNIEnv *, jobject);

/*
 * Class:     fang_key_CheckKey
 * Method:    getAPPKeyFile
 * Signature: (Ljava/lang/String;)
 */
JNIEXPORT jstring JNICALL Java_fang_key_CheckKey_getAPPKeyFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
